name: Deploy to Pages
on: [push]

jobs:
  build_pdf:
    defaults:
      run:
        working-directory: /home/runner/work/CoEnv/CoEnv/doku/ethics
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          extra_system_packages: "inkscape"
          working_directory: /home/runner/work/CoEnv/CoEnv/doku/ethics
          latexmk_shell_escape: true
          root_file: |
            coenv.tex
            garments_digital.tex
            presentation.tex

      - name: Move PDFs
        continue-on-error: true
        run: ls && mv *.pdf public/

      - name: Install latex2html
        run: sudo apt-get install -y latex2html

      - name: Build HTML
        continue-on-error: true
        run: make html

  build_entp_marketing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doku/entp-marketing
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true
          
      - run: "pnpm build"
        env:
          BASE_PATH: /${{ github.event.repository.name }}

  build_symbol:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: symbol-creator
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - run: pnpm build
        env:
          BASE_URL: ${{ github.event.repository.name }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build_symbol,build_entp_marketing,build_pdf]
    steps:
      - run: mkdir -p "tmp/deploy"
      - run: cp -r symbol-creator/build tmp/deploy/symbol
      - run: cp -r doku/entp-marketing/build tmp/deploy/marketing
      - run: cp -r doku/ethics/public tmp/deploy/ethics
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: tmp/deploy # The folder the action should deploy.
