name: Deploy to Pages
on: [push]

jobs:
  build_ethics:
    defaults:
      run:
        working-directory: doku/ethics/
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          extra_system_packages: "inkscape"
          working_directory: doku/ethics
          latexmk_shell_escape: true
          root_file: "*.tex"
          glob_root_file: true

      - name: Move PDFs
        continue-on-error: true
        run: ls && mv *.pdf public/

      - name: Install latex2html
        run: sudo apt update && sudo apt-get install -y latex2html

      - name: Build HTML
        continue-on-error: true
        run: make html

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ethics-output
          path: doku/ethics/public/*
          retention-days: 1

  build_entp_marketing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doku/entp-marketing
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - run: "pnpm build"
        env:
          BASE_PATH: /${{ github.event.repository.name }}/marketing

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: marketing-output
          path: doku/entp-marketing/build/*
          retention-days: 1

  build_symbol:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: symbol-creator
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - run: pnpm build
        env:
          BASE_URL: ${{ github.event.repository.name }}/symbol/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: symbol-creator-output
          path: symbol-creator/build
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: [build_symbol, build_entp_marketing, build_ethics]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - run: mkdir -p "tmp/deploy"
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: symbol-creator-output
          path: symbol-creator/build
      - run: cp -r symbol-creator/build .github/pages/symbol
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: marketing-output
          path: doku/entp-marketing/build
      - run: cp -r doku/entp-marketing/build .github/pages/marketing
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ethics-output
          path: doku/ethics/public
      - run: cp -r doku/ethics/public .github/pages/ethics
      - run: cd .github/pages && for d in ./* ; do cd $d && touch .nojekyll && cd ..; done
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .github/pages # The folder the action should deploy.
